# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

formats:
  - epub

sphinx:
  configuration: docs/conf.py

python:
  install:
  - requirements: requirements.txt
  - requirements: requirements-dev.txt
  - requirements: requirements-docs.txt
