[tox]
envlist=py34-syntax, py27-flake8, py34-flake8, py27, py34, py27-coverage, py34-extres, py27-extres

[testenv]
commands=nosetests -vs -x --tests=tests/static/,tests/live_tests/
deps=nose
passenv=TRAVIS BUILD_ONLY

[testenv:py34-extres]
basepython=python3.4
commands=nosetests -vs --tests=tests/external_resources/
deps=nose

[testenv:py27-extres]
basepython=python2.7
commands=nosetests -vs --tests=tests/external_resources/
deps=nose

[testenv:py34-syntax]
basepython=python3.4
whitelist_externals=bash
commands=bash -c "find pierky/ scripts/ tests/ -name "*.py" | xargs python -m py_compile"
deps=

[testenv:py27-flake8]
basepython=python2.7
deps=flake8
commands=flake8 pierky/ scripts/

[testenv:py34-flake8]
basepython=python3.4
deps=flake8
commands=flake8 pierky/ scripts/

[testenv:py27-coverage]
basepython=python2.7
setenv=BUILD_ONLY=1
commands=
  coverage run --source=pierky --omit="pierky/arouteserver/tests/*" --branch setup.py nosetests --stop --verbosity=2 --tests=tests/static/,tests/live_tests/
  coverage report -m
deps=
  nose
  coverage

[flake8]
# https://pycodestyle.readthedocs.io/en/latest/intro.html#error-codes
ignore =
  # Indentation, continuation line...
  E12,
  # Whitespace
  E2,
  # Blank line
  E3,
  # Line length
  E5,
  # Bare except
  E722,
  # F405: x may be undefined, or defined from star imports
  F405,
  # F403 'from .x import *' used; unable to detect undefined names
  F403,
