#!/bin/bash

if [ ! -e "setup.py" ]; then
	echo "The script must be executed from within the repository's root directory."
	exit 1
fi

export PYTHONPATH="`pwd`"

RES_FILE=`mktemp`
echo 0 > $RES_FILE

function reset() {
	AROUTESERVER="./scripts/arouteserver"
	CFG_FILE="var/build_doc.yml"
	GENERAL="config.d/general.yml"
	CLIENTS="config.d/clients.yml"
	BOGONS="config.d/bogons.yml"
}

function build_cmd() {
	COMMAND="$1" ; shift
	$AROUTESERVER $COMMAND --cfg $CFG_FILE --general $GENERAL --clients $CLIENTS --bogons $BOGONS $@ 2>&1
}

function run_cmd() {
	COMMAND="$1" ; shift
	$AROUTESERVER $COMMAND --cfg $CFG_FILE $@ 2>&1
}

function error() {
	echo "$1"
	echo 1 > $RES_FILE
}

function must_contain() {
	grep "$1" &>/dev/null || error "Fail: \"$1\" not found."
}

function must_not_contain() {
	grep "$1" &>/dev/null

	if [ $? -eq 0 ]; then
		error "Fail: \"$1\" found."
	fi
}

# clients-from-euroix
reset

# 0.4 schema version:
run_cmd "clients-from-euroix" --url https://my.ams-ix.net/api/v1/members.json 1 | must_contain "description: Akamai"
# 0.5 schema version:
run_cmd "clients-from-euroix" --url https://portal.lonap.net/apiv1/member-list/list 1 | must_contain "AS-APPLE"
# 0.6 schema version:
run_cmd "clients-from-euroix" --url https://www.swissix.ch/euroix/create-json-ixp-member-list.php 1 | must_contain "description: Microsoft"

reset
build_cmd "openbgpd" | must_contain "ERROR Compatibility issue ID 'path_hiding'"

reset
GENERAL="tests/var/general.yml"
cat << EOF > $GENERAL
cfg:
  rs_as: 999
  router_id: "192.0.2.2"
  communities:
    do_not_announce_to_peer:
      lrg: "rs_as:0:peer_as"
EOF
build_cmd "openbgpd" | must_contain "ERROR Compatibility issue ID 'large_communities'. The community 'do_not_announce_to_peer'"
build_cmd "openbgpd" --target-version 6.0 | must_contain "ERROR Compatibility issue ID 'large_communities'. The community 'do_not_announce_to_peer'"
build_cmd "openbgpd" --target-version 6.1 | must_not_contain "ERROR Compatibility issue ID 'large_communities'"

reset
GENERAL="tests/var/general.yml"
cat << EOF > $GENERAL
cfg:
  rs_as: 999
  router_id: "192.0.2.2"
  blackhole_filtering:
    policy_ipv6: 'rewrite-next-hop'
    rewrite_next_hop_ipv6: '2001:db8:1:1::66'
EOF
build_cmd "openbgpd" | must_contain "Compatibility issue ID 'blackhole_filtering_rewrite_ipv6_nh'. On OpenBSD < 6.1"
build_cmd "openbgpd" --target-version 6.0 | must_contain "Compatibility issue ID 'blackhole_filtering_rewrite_ipv6_nh'. On OpenBSD < 6.1"
build_cmd "openbgpd" --target-version 6.1 | must_not_contain "Compatibility issue ID 'blackhole_filtering_rewrite_ipv6_nh'"

ERROR=`cat $RES_FILE`
if [ $ERROR -eq 1 ]; then
	echo "Done! ERRORS FOUND"
else
	echo "Done!"
fi
rm $RES_FILE

exit $ERROR
