#!/bin/bash

INSTANCE_NAME="rs"
CURR_DIR=`dirname -- "$0"`

shift

ssh -o BatchMode=yes -o ConnectTimeout=5 -o ServerAliveInterval=10 -o StrictHostKeyChecking=no root@192.0.2.2 -i ~/.ssh/arouteserver bgpctl "$@"
