#!/bin/bash

if [ ! -e "setup.py" ]; then
	echo "The script must be executed from within the repository's root directory."
	exit
fi

DOCS_DIR="`pwd`/docs"

echo "Building Live scenarios TOC"
rm $DOCS_DIR/LIVETESTS_SCENARIOS_*.rst

echo ".. toctree::" > $DOCS_DIR/LIVETESTS_SCENARIOS.rst
echo "   :maxdepth: 1" >> $DOCS_DIR/LIVETESTS_SCENARIOS.rst
echo "" >> $DOCS_DIR/LIVETESTS_SCENARIOS.rst

cd tests/live_tests/scenarios/
for d in */; do
	SCENARIO_NAME=`basename $d`
	if [ -e "$SCENARIO_NAME/README.rst" ]; then
		echo ".. include:: ../tests/live_tests/scenarios/$SCENARIO_NAME/README.rst" > $DOCS_DIR/LIVETESTS_SCENARIOS_$SCENARIO_NAME.rst
		echo "   LIVETESTS_SCENARIOS_$SCENARIO_NAME" >> $DOCS_DIR/LIVETESTS_SCENARIOS.rst
	fi
done

cd $DOCS_DIR
cd ..

CFG_FILE="var/arouteserver.yml"

CMD="./scripts/arouteserver build --cfg $CFG_FILE --general config.d/general.yml --clients config.d/clients.yml --bogons config.d/bogons.yml"

echo "Building example: default, IPv4"
$CMD --ip-ver 4 > examples/default/bird4.conf

echo "Building example: default, IPv6"
$CMD --ip-ver 6 > examples/default/bird6.conf

CMD="./scripts/arouteserver build --cfg $CFG_FILE --general examples/rich/general.yml --clients examples/rich/clients.yml --bogons config.d/bogons.yml"

echo "Building example: rich, IPv4"
$CMD --ip-ver 4 > examples/rich/bird4.conf

echo "Building example: rich, IPv6"
$CMD --ip-ver 6 > examples/rich/bird6.conf

echo "Building README.rst"

cat $DOCS_DIR/README_header.txt > README.rst
cat $DOCS_DIR/FEATURES.rst >> README.rst
cat $DOCS_DIR/README_footer.txt >> README.rst


cd $DOCS_DIR
make html
cd _build/html/
python -m SimpleHTTPServer 8000
cd ../../../
